version: '3'

services:
    client:
        build: ./client
        ports:
            - 8080:8080
        volumes:
            - ./client:/client
    server:
        build: ./server
        ports:
            - 3000:3000
        volumes:
            - ./server:/server
